image:
  repository: ghcr.io/luissimas/zettelkasten-exporter
  tag: latest

zettelkasten:
  # -- The directory where your Zettelkasten is located.
  directory: ""
  git:
    url: "https://github.com/luissimas/sample-zettelkasten"
    branch: "main"
  # -- Provide a GitHub token as a string (will be base64 encoded)
  githubToken: ""
  # -- Or, provide the name of an existing secret and the key within it
  existingSecret:
    name: ""
    key: ""
  # -- A list of files to ignore when collecting metrics.
  ignoreFiles:
    - .git
    - .obsidian
    - .trash
    - README.md

collectionInterval: "30s"
# -- Collect historical metrics from the git history.
collectHistoricalMetrics: true
logLevel: "INFO"

vm:
  enabled: true
  server:
    retentionPeriod: 60 # 5y

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - k8s.local
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          url: http://{{ .Release.Name }}-vm-server:8428
          access: proxy
          isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: "zettelkasten-dashboard"
