{{- if and .Values.zettelkasten.githubToken (not .Values.zettelkasten.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zettelkasten-exporter.fullname" . }}-env
type: Opaque
data:
  github-token: {{ .Values.zettelkasten.githubToken | b64enc | quote }}
{{- end -}}