{
 "title": "Zettelkasten",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New notes",
   "type": "stat",
   "description": "Number of notes created in the visualization period",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_note_count[$__range])",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\" and r[\"_field\"] == \"note_count\")\n  |> spread()"
    }
   ]
  },
  {
   "title": "New links",
   "type": "stat",
   "description": "Number of links created in the visualization period",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_link_count[$__range])",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\" and r[\"_field\"] == \"link_count\")\n  |> spread()"
    }
   ]
  },
  {
   "title": "New words",
   "type": "stat",
   "description": "Number of words written in the visualization period",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_word_count[$__range])",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\" and r[\"_field\"] == \"word_count\")\n  |> spread()"
    }
   ]
  },
  {
   "title": "Reading time",
   "type": "stat",
   "description": "Time to read all notes created in the visualization period",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(total_word_count[$__range]) / 212, 1)",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\" and r[\"_field\"] == \"word_count\")\n  |> map(fn: (r) => ({r with _value: r._value / uint(v: 212)}))\n  |> spread()"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "table",
   "description": "Metrics from each markdown note in the Zettelkasten",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "notes_link_count",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"notes\")\n  |> last()\n  |> pivot(rowKey: [\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _measurement: r._measurement,\n    name: r.name,\n    backlink_count: r.backlink_count,\n    link_count: r.link_count,\n    word_count: r.word_count,\n    time_to_read: r.word_count / uint(v: 212)\n    }))\n  |> group()"
    },
    {
     "expr": "notes_backlink_count",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"notes\")\n  |> last()\n  |> pivot(rowKey: [\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _measurement: r._measurement,\n    name: r.name,\n    backlink_count: r.backlink_count,\n    link_count: r.link_count,\n    word_count: r.word_count,\n    time_to_read: r.word_count / uint(v: 212)\n    }))\n  |> group()"
    },
    {
     "expr": "notes_word_count",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"notes\")\n  |> last()\n  |> pivot(rowKey: [\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _measurement: r._measurement,\n    name: r.name,\n    backlink_count: r.backlink_count,\n    link_count: r.link_count,\n    word_count: r.word_count,\n    time_to_read: r.word_count / uint(v: 212)\n    }))\n  |> group()"
    },
    {
     "expr": "round(notes_word_count / 212, 1)",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"notes\")\n  |> last()\n  |> pivot(rowKey: [\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _measurement: r._measurement,\n    name: r.name,\n    backlink_count: r.backlink_count,\n    link_count: r.link_count,\n    word_count: r.word_count,\n    time_to_read: r.word_count / uint(v: 212)\n    }))\n  |> group()"
    }
   ]
  },
  { "title": "Historical data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Notes",
   "type": "timeseries",
   "description": "Historical evolution of the number of notes in the Zettelkasten",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "total_note_count",
     "legendFormat": "Note count",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"note_count\")"
    }
   ]
  },
  {
   "title": "Words",
   "type": "timeseries",
   "description": "Historical evolution of words in the Zettelkasten",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "total_word_count",
     "legendFormat": "Word count",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"word_count\")"
    }
   ]
  },
  {
   "title": "Links",
   "type": "timeseries",
   "description": "Historical evolution of the number of links in the Zettelkasten",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "total_link_count",
     "legendFormat": "Link count",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"link_count\")"
    }
   ]
  },
  {
   "title": "Reading time",
   "type": "timeseries",
   "description": "Historical evolution of the total reading time for the Zettelkasten",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "total_word_count / 212",
     "legendFormat": "Reading time",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"word_count\")\n  |> map(fn: (r) => ({r with _value: r._value / uint(v: 212)}))"
    }
   ]
  },
  {
   "title": "Average link count",
   "type": "timeseries",
   "description": "Historical evolution of the average number of links per note in the Zettelkasten",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(notes_link_count[$__range]) / count(notes_link_count[$__range])",
     "legendFormat": "Link count",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"notes\" and r[\"_field\"] == \"link_count\")\n  |> group(columns: [\"__time\"])\n  |> aggregateWindow(\n   every: v.windowPeriod,\n   fn: (column, tables=<-) => tables |> mean(),\n   column: \"name\",\n   createEmpty: false\n)"
    }
   ]
  },
  {
   "title": "Average word count",
   "type": "timeseries",
   "description": "Historical evolution of the average number of words per note in the Zettelkasten",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(notes_word_count[$__range]) / count(notes_word_count[$__range])",
     "legendFormat": "Word count",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"notes\" and r[\"_field\"] == \"word_count\")\n  |> group(columns: [\"__time\"])\n  |> aggregateWindow(\n   every: v.windowPeriod,\n   fn: (column, tables=<-) => tables |> mean(),\n   column: \"name\",\n   createEmpty: false\n)"
    }
   ]
  }
 ]
}