{
 "title": "Zettelkasten",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "New notes this week",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/date/boundaries\"\n\nlastWeek = boundaries.week(week_offset: -1)\n\nfrom(bucket: v.defaultBucket)\n|> range(start: lastWeek.start)\n|> group()\n|> aggregateWindow(\n   every: 1w,\n   fn: (column, tables=<-) => tables |> distinct(column: column) |> count(),\n   column: \"name\",\n   createEmpty: false\n)\n|> increase()\n|> last()"
    }
   ]
  },
  {
   "title": "New links this week",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/date/boundaries\"\n\nlastWeek = boundaries.week(week_offset: -1)\n\nfrom(bucket: v.defaultBucket)\n|> range(start: lastWeek.start)\n|> group()\n|> aggregateWindow(\n   every: 1w,\n   fn: (column, tables=<-) => tables |> group(columns: [\"name\", \"_start\", \"_stop\"]) |> last() |> group(columns: [\"_start\", \"_stop\"]) |> sum(),\n   column: \"name\",\n   createEmpty: false\n)\n|> increase()\n|> last()"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> last()\n|> group()"
    }
   ]
  },
  {
   "title": "Note count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> group()\n|> aggregateWindow(\n   every: v.windowPeriod,\n   fn: (column, tables=<-) => tables |> distinct(column: column) |> count(),\n   column: \"name\",\n   createEmpty: false\n)"
    }
   ]
  },
  {
   "title": "Link count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> group()\n|> aggregateWindow(\n   every: v.windowPeriod,\n   fn: (column, tables=<-) => tables |> group(columns: [\"name\", \"_start\", \"_stop\"]) |> last() |> group(columns: [\"_start\", \"_stop\"]) |> sum(),\n   column: \"name\",\n   createEmpty: false\n)"
    }
   ]
  }
 ]
}