name: Release Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-chart:
    uses: ./.github/workflows/check-chart.yaml

  publish-chart:
    needs: check-chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'

      - name: Get version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Update Chart.yaml
        run: |
          yq e -i '.version = "${{ steps.get_version.outputs.VERSION }}" | .appVersion = "${{ steps.get_version.outputs.VERSION }}"' charts/zettelkasten-exporter/Chart.yaml

      - name: List helm repositories
        id: list_helm_repos
        uses: mikefarah/yq@v4.45.4
        with:
          cmd: yq e '.dependencies[] | .name + " " + .repository' charts/zettelkasten-exporter/Chart.yaml

      - name: Add helm repositories
        run: |
          echo "${{ steps.list_helm_repos.outputs.result }}" | while read -r repo; do
            helm repo add $repo
          done

      - name: Package Helm chart
        run: helm package ./charts/zettelkasten-exporter --dependency-update

      - name: Push Helm chart to GHCR
        run: |
          helm push zettelkasten-exporter-${{ steps.get_version.outputs.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/zettelkasten-exporter-chart
